# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 11:51
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0004_disable_repositories_and_add_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositrecord',
            name='additional_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depositrecord',
            name='splash_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='depositrecord',
            name='upload_type',
            field=models.CharField(choices=[('preprint', 'Preprint'), ('postprint', 'Postprint'), ('pdfversion', 'Published version')], max_length=64),
        ),
    ]
