# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0005_add_fields_to_depositrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending publication'), ('published', 'Published'), ('refused', 'Refused by the repository'), ('deleted', 'Deleted')], default='published', max_length=64),
            preserve_default=False,
        ),
    ]
