# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 14:58


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0009_populate_last_repository'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='email',
            field=models.EmailField(blank=True, help_text='We will use this email address to notify you when your deposits are accepted.', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='preferred_repository',
            field=models.ForeignKey(blank=True, help_text='This repository will be used by default for your deposits.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferred_by', to='deposit.Repository'),
        ),
    ]
