# Generated by Django 2.2.1 on 2019-05-15 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0010_email_on_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositrecord',
            name='oairecord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='papers.OaiRecord'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='last_repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_used_by', to='deposit.Repository'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='preferred_repository',
            field=models.ForeignKey(blank=True, help_text='This repository will be used by default for your deposits.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by', to='deposit.Repository'),
        ),
    ]
