# Generated by Django 2.2.1 on 2019-05-16 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0011_nullable_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('identifier', models.CharField(max_length=50)),
                ('uri', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.BooleanField(default=False)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deposit.License')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deposit.Repository')),
            ],
        ),
        migrations.AddField(
            model_name='repository',
            name='licenses',
            field=models.ManyToManyField(through='deposit.DefaultLicense', to='deposit.License'),
        ),
    ]
