# Generated by Django 2.2.1 on 2019-05-15 14:53

from django.db import migrations

def create_standard_licenses(apps, schema_editor):
    """
    Creates a set of standard licenses
    """
    License = apps.get_model('deposit', 'License')

    licenses = [
        { 
            'name' : 'Creative Commons 1.0 Universal (CC0 1.0) Public Domain Dedication',
            'identifier' : 'CC0-1.0',
            'uri' : 'https://creativecommons.org/publicdomain/zero/1.0/',
        },
        { 
            'name' : 'Creative Commons 1.0 Universal (CC0 1.0) Public Domain Dedication',
            'identifier' : '563c1cf88c5e4a3877f9e96c',
            'uri' : 'https://creativecommons.org/publicdomain/zero/1.0/',
        },
        {
            'name' : 'Creative Commons Attribution 4.0 International (CC BY 4.0)',
            'identifier' : 'CC-BY-4.0',
            'uri' : 'https://creativecommons.org/licenses/by/4.0/',
        },
        {
            'name' : 'Creative Commons Attribution 4.0 International (CC BY 4.0)',
            'identifier' : '563c1cf88c5e4a3877f9e96a',
            'uri' : 'https://creativecommons.org/licenses/by/4.0/',
        },
        {
            'name' : 'Creative Commons Attribution-ShareAlike 4.0, International (CC BY-SA 4.0)',
            'identifier' : 'CC-BY-SA-4.0',
            'uri' : 'https://creativecommons.org/licenses/by-sa/4.0/',
        },
        {
            'name' : 'Creative Commons Attribution-NonCommerical 4.0 International (CC BY-NC 4.0)',
            'identifier' : 'CC-BY-NC-4.0',
            'uri' : 'https://creativecommons.org/licenses/by-nc/4.0/',
        },
        {
            'name' : 'Creative Commons Attribution-NoDerivatives 4.0 International (CC BY-ND 4.0)',
            'identifier' : 'CC-BY-ND-4.0',
            'uri' : 'http://creativecommons.org/licenses/by-nd/4.0/',
        },
        {
            'name' : 'Free for private use; right holder retains other rights, including distribution',
            'identifier' : 'zenodo-freetoread-1.0',
        },
        {
            'name' : 'Other open license',
            'identifier' : 'other-open',
        },
        {
            'name' : 'No license',
            'identifier' : '563c1cf88c5e4a3877f9e965',
        },
    ]

    License.objects.bulk_create([License(**license) for license in licenses])

    """
    We populate for the existing repos the many2many. That is: Zenodo and OSF
    """

    Repository = apps.get_model('deposit', 'Repository')
    DefaultLicense = apps.get_model('deposit', 'DefaultLicense')

    repos_zenodo = Repository.objects.filter(protocol='ZenodoProtocol')
    for repo in repos_zenodo:
        # Default license
        license = License.objects.get(identifier='zenodo-freetoread-1.0')
        DefaultLicense.objects.create(repository=repo, license=license, default=True)
        # Non-default licenses
        for license_id in ['CC0-1.0', 'CC-BY-4.0', 'CC-BY-SA-4.0', 'CC-BY-NC-4.0', 'CC-BY-ND-4.0', 'other-open']:
            license = License.objects.get(identifier=license_id)
            DefaultLicense.objects.create(repository=repo, license=license, default=False)

    repos_osf = Repository.objects.filter(protocol='OSFProtocol')
    for repo in repos_osf:
        # Default license
        license = License.objects.get(identifier='563c1cf88c5e4a3877f9e965')
        DefaultLicense.objects.create(repository=repo, license=license, default=True)
        # Non-default licenses
        for license_id in ['563c1cf88c5e4a3877f9e96c', '563c1cf88c5e4a3877f9e96a']:
            license = License.objects.get(identifier=license_id)
            DefaultLicense.objects.create(repository=repo, license=license, default=False)


        

def remove_standard_licenses(apps, schema_editor):
    """
    Removes the licenses
    """
    License = apps.get_model('deposit', 'License')
    License.objects.all().delete()
    DefaultLicense = apps.get_model('deposit', 'DefaultLicense')
    DefaultLicense.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0012_licenses'),
    ]

    operations = [
        migrations.RunPython(create_standard_licenses, remove_standard_licenses)
    ]
