# Generated by Django 2.2.4 on 2019-08-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0016_populate_ddc'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='abstract_required',
            field=models.BooleanField(default=True),
        ),
    ]
