# Generated by Django 2.2.4 on 2019-10-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0018_letter_of_declaration'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositrecord',
            name='pub_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='embargo',
            field=models.CharField(choices=[('none', 'None'), ('optional', 'Optional'), ('required', 'Required')], default='none', max_length=24),
        ),
        migrations.AlterField(
            model_name='depositrecord',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
