# Generated by Django 2.2.7 on 2019-11-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0020_embargo_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='update_status_url',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='depositrecord',
            name='status',
            field=models.CharField(choices=[('failed', 'Failed'), ('faked', 'Faked'), ('pending', 'Pending publication'), ('embargoed', 'Embargo'), ('published', 'Published'), ('refused', 'Refused by the repository'), ('deleted', 'Deleted')], default='failed', max_length=64),
        ),
    ]
