# Generated by Django 2.2.7 on 2019-12-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0021_update_deposit_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='depositrecord',
            index=models.Index(fields=['status', '-pub_date'], name='papers_depo_status_268444_idx'),
        ),
    ]
