# Generated by Django 2.2.7 on 2020-01-07 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0022_deposit_record_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenOpenAccessService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField()),
                ('text', models.TextField()),
                ('learn_more_url', models.URLField(max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='repository',
            name='goa_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deposit.GreenOpenAccessService'),
        ),
    ]
