# Generated by Django 2.2.7 on 2020-01-21 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0023_green_oa_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterOfDeclaration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField()),
                ('text', models.TextField()),
                ('url_text', models.CharField(max_length=100)),
                ('function_key', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='repository',
            name='letter_declaration',
        ),
        migrations.AddField(
            model_name='repository',
            name='letter_declaration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deposit.LetterOfDeclaration'),
        ),
    ]
