# Generated by Django 2.2.12 on 2020-04-08 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0024_extend_letter_of_declaration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='letter_declaration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deposit.LetterOfDeclaration'),
        ),
    ]
