# Generated by Django 2.2.16 on 2020-10-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0025_letter_declaration_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='letterofdeclaration',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='letterofdeclaration',
            name='function_key',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
