# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 10:40
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0026_delete_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='authors_list',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
