# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-06 21:05


from django.db import migrations, models
import django.db.models.deletion
import papers.models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0026_delete_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperworld',
            name='stats',
            field=models.ForeignKey(default=papers.models.create_default_stats, on_delete=django.db.models.deletion.CASCADE, to='statistics.AccessStatistics'),
        ),
    ]
