# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 20:51


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0031_remove_annotation_simplify_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oairecord',
            name='doi',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
