# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 18:13


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0032_doi_not_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oairecord',
            name='abstract',
        ),
    ]
