# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-22 19:19


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0027_alter_paperworld'),
        ('papers', '0033_remove_oairecord_abstract'),
    ]

    operations = [
    ]
