# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-14 05:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0036_paper_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='last_modified',
        ),
        migrations.RenameField(
            model_name='paper',
            old_name='temp',
            new_name='last_modified',
        ),

    ]
