# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-15 06:12


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0037_remove_paper_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
