# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def populate_institutions(apps, se):
    Researcher = apps.get_model('papers', 'Researcher')
    for r in Researcher.objects.all():
        if r.department:
            r.institution_id = r.department.institution_id
            r.save()

def backwards(apps, se):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0039_populate_oai_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='identifier',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='researcher',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='papers.Institution'),
        ),
        migrations.RunPython(populate_institutions, backwards),
    ]
