# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0040_institutions_for_orcid'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='country',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
