# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 08:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations

def populate_records(apps, schema_editor):
    Paper = apps.get_model('papers', 'Paper')
    OaiRecord = apps.get_model('papers', 'OaiRecord')

    lastpk = 100000
    bs = 500
    found = True
    while found:
        found = False
        print lastpk
    
        papers = list(Paper.objects.filter(pk__gt=lastpk).order_by('id')[:bs])
        if not papers:
            break
        found = True

        new_lastpk = papers[-1].pk

        records_list = OaiRecord.objects.filter(about_id__gt=lastpk,
                about_id__lte=new_lastpk)
        records = defaultdict(list)
        for record in records_list:
            records[record.about_id].append(record)
        
        updated = []
        for p in papers:
            for r in records[p.id]:
                p.add_oairecord(r)
            updated.append(p)
        bulk_update(updated, update_fields=['records_list'])
        lastpk = new_lastpk

def do_nothing(apps, schema_editor):
    pass



class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('papers', '0041_populate_identifiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='records_list',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.RunPython(populate_records, do_nothing),
    ]
