# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 08:49
from __future__ import unicode_literals

from bulk_update.helper import bulk_update
from collections import defaultdict
import django.contrib.postgres.fields.jsonb
from django.db import migrations

class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('papers', '0041_populate_identifiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='records_list',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
