# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 23:36


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0041_institution_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='homepage',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
