# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0043_fill_records_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oairecord',
            name='about',
        ),
        migrations.RemoveField(
            model_name='oairecord',
            name='journal',
        ),
        migrations.RemoveField(
            model_name='oairecord',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='oairecord',
            name='source',
        ),
        migrations.DeleteModel(
            name='OaiRecord',
        ),
    ]
