# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 20:41


from django.db import migrations
from django_countries.fields import countries

def backwards(apps, se):
    pass

def cleanup(apps, se):
    i = apps.get_model('papers', 'Institution')
    for inst in i.objects.all():
        if inst.country.code not in countries:
            inst.country = None
            inst.save(update_fields=['country'])

class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0045_institution_coords'),
    ]

    operations = [
        migrations.RunPython(cleanup, backwards),
    ]
