# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 20:41
from __future__ import unicode_literals

from django.db import migrations

def backwards(apps, se):
    pass

def cleanup(apps, se):
    Researcher = apps.get_model('papers', 'Researcher')
    for r in Researcher.objects.filter(orcid__isnull=False):
        for p in r.paper_set.all():
            # Check if the researcher appears with its ORCID id
            disambiguated_via_orcid = False
            pos = None
            for idx, a in enumerate(p.authors):
                if a.researcher_id == r.id:
                    pos = idx
                    if a.orcid == r.orcid:
                        disambiguated_via_orcid = True
            # if not, remove it from the paper
            if not disambiguated_via_orcid and pos:
                p.authors_list[pos]['researcher_id'] = None
                p.researchers.remove(r)
                p.save(update_fields=['authors_list'])

class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0046_cleanup_countries'),
    ]

    operations = [
        migrations.RunPython(cleanup, backwards),
    ]
