# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-05 12:01


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0047_cleanup_orcid_researchers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='researchers',
        ),
    ]
