# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-05 12:01

import datetime
from papers.utils import year_margin
from django.db import migrations
import haystack
from papers.models import Paper


# have to put this here as we cannot call methods from the model in a migration...

def remove_from_index(paper):
    """
    Remove this paper from Haystack's index
    (to be called before deleting the paper for real)
    """
    using_backends = haystack.connection_router.for_write(instance=paper)
    for using in using_backends:
        try:
            index = haystack.connections[using].get_unified_index(
                                    ).get_index(Paper)
            index.remove_object(paper, using=using)
        except haystack.exceptions.NotHandled:
            pass


def database_forwards(apps, schema_editor):
    now = datetime.datetime.now()
    current_year = now.year
    cutoff_date = datetime.datetime(current_year + year_margin, 12, 31)
    Paper_fake = apps.get_model("papers", "Paper")
    for paper in Paper_fake.objects.filter(pubdate__gt=cutoff_date):
        remove_from_index(paper)
        paper.delete()


def database_backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0048_remove_paper_researchers'),
    ]

    operations = [
        migrations.RunPython(
            database_forwards,
            database_backwards
        ),
    ]
