# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-09 11:05


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0049_filter_future_dates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oaisource',
            old_name='last_status_update',
            new_name='last_update',
        ),
    ]
