# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-16 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0052_researcher_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='oaisource',
            name='endpoint',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='oaisource',
            name='restrict_set',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='papers.Department'),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='stats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='statistics.AccessStatistics'),
        ),
    ]
