# Generated by Django 2.1.7 on 2019-03-26 19:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import papers.models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0054_populate_oai_endpoints'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='namevariant',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='namevariant',
            name='name',
        ),
        migrations.RemoveField(
            model_name='namevariant',
            name='researcher',
        ),
        migrations.AlterField(
            model_name='oairecord',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publishers.Journal'),
        ),
        migrations.AlterField(
            model_name='oairecord',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publishers.Publisher'),
        ),
        migrations.AlterField(
            model_name='oaisource',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='paperworld',
            name='stats',
            field=models.ForeignKey(default=papers.models.create_default_stats, on_delete=django.db.models.deletion.SET_DEFAULT, to='statistics.AccessStatistics'),
        ),
        migrations.DeleteModel(
            name='NameVariant',
        ),
    ]
