# Generated by Django 2.2.4 on 2019-08-22 14:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('papers', '0056_remove_unused_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='todolist',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
