# Generated by Django 2.2.10 on 2020-02-19 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0058_correct_crossref_pub_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='coords',
        ),
    ]
