#coding:utf-8
gettext('Computer science, knowledge & systems')
gettext('Bibliographies')
gettext('Library & information sciences')
gettext('Encyclopedias & books of facts')
gettext('Magazines, journals & serials')
gettext('Associations, organizations & museums')
gettext('News media, journalism & publishing')
gettext('Quotations')
gettext('Manuscripts & rare books')
gettext('Philosophy')
gettext('Metaphysics')
gettext('Epistemology')
gettext('Parapsychology & occultism')
gettext('Philosophical schools of thought')
gettext('Psychology')
gettext('Philosophical logic')
gettext('Ethics')
gettext('Ancient, medieval & eastern philosophy')
gettext('Modern western philosophy')
gettext('Religion')
gettext('Philosophy & theory of religion')
gettext('The Bible')
gettext('Christianity')
gettext('Christian practice & observance')
gettext('Christian pastoral practice & religious orders')
gettext('Christian organization, social work & worship')
gettext('History of Christianity')
gettext('Christian denominations')
gettext('Other religions')
gettext('Social sciences, sociology & anthropology')
gettext('Statistics')
gettext('Political science')
gettext('Economics')
gettext('Law')
gettext('Public administration & military science')
gettext('Social problems & social services')
gettext('Education')
gettext('Commerce, communications & transportation')
gettext('Customs, etiquette & folklore')
gettext('Language')
gettext('Linguistics')
gettext('English & Old English languages')
gettext('German & related languages')
gettext('French & related languages')
gettext('Italian, Romanian & related languages')
gettext('Spanish, Portuguese, Galician')
gettext('Latin & Italic languages')
gettext('Classical & modern Greek languages')
gettext('Other languages')
gettext('Science')
gettext('Mathematics')
gettext('Astronomy')
gettext('Physics')
gettext('Chemistry')
gettext('Earth sciences & geology')
gettext('Fossils & prehistoric life')
gettext('Biology')
gettext('Plants (Botany)')
gettext('Animals (Zoology)')
gettext('Technology')
gettext('Medicine & health')
gettext('Engineering')
gettext('Agriculture')
gettext('Home & family management')
gettext('Management & public relations')
gettext('Chemical engineering')
gettext('Manufacturing')
gettext('Manufacture for specific uses')
gettext('Construction of buildings')
gettext('Arts')
gettext('Area planning & landscape architecture')
gettext('Architecture')
gettext('Sculpture, ceramics & metalwork')
gettext('Graphic arts & decorative arts')
gettext('Painting')
gettext('Printmaking & prints')
gettext('Photography, computer art, film, video')
gettext('Music')
gettext('Sports, games & entertainment')
gettext('Literature, rhetoric & criticism')
gettext('American literature in English')
gettext('English & Old English literatures')
gettext('German & related literatures')
gettext('French & related literatures')
gettext('Italian, Romanian & related literatures')
gettext('Spanish, Portuguese, Galician literatures')
gettext('Latin & Italic literatures')
gettext('Classical & modern Greek literatures')
gettext('Other literatures')
gettext('History')
gettext('Geography & travel')
gettext('Biography & genealogy')
gettext('History of ancient world (to ca. 499)')
gettext('History of Europe')
gettext('History of Asia')
gettext('History of Africa')
gettext('History of North America')
gettext('History of South America')
gettext('History of other areas')
gettext('Data processing & computer science')
gettext('Military science')
gettext('Other Germanic languages')
gettext('Public performances')
gettext('Stage presentations')
gettext('Indoor games & amusements')
gettext('Athletic & outdoor sports & games')
gettext('Other Germanic literatures')
gettext('Germany & neighboring central European countries')
gettext('Green Open Access Service')
gettext('Would you like that the University and State Library Darmstadt publishes your publications green open access for you?\n<br/>\nContact us: <a href="mailto:dpub@ulb-tu-darmstadt.de">dpub@ulb-tu-darmstadt.de</a>')
gettext('TUprints contract required!')
gettext('For every document, that you upload via Dissemin we need once a TUprints contract.\nPlease fill in the contract and send a printed and signed copy to:\n<br>\nULB Darmstadt, Team Digitales Publizieren, Magdalenenstr. 8, 64289 Darmstadt')
gettext('Download contract')
gettext('Creative Commons 1.0 Universal (CC0 1.0) Public Domain Dedication')
gettext('Creative Commons Attribution 4.0 International (CC BY 4.0)')
gettext('Creative Commons Attribution-ShareAlike 4.0, International (CC BY-SA 4.0)')
gettext('Creative Commons Attribution-NonCommerical 4.0 International (CC BY-NC 4.0)')
gettext('Creative Commons Attribution-NoDerivatives 4.0 International (CC BY-ND 4.0)')
gettext('Free for private use; right holder retains other rights, including distribution')
gettext('Other open license')
gettext('No license')
gettext('Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)')
gettext('Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International (CC BY-NC-ND 4.0)')
gettext('Zenodo')
gettext('Zenodo is a general-purpose open repository hosted by CERN. If the document does not have a DOI yet, Zenodo will create one.')
gettext('HAL')
gettext('HAL is a  multidisciplinary open archive, sustained by the French Research Ministry.')
gettext('OSF preprints')
gettext('Run by the Center for Open Science, OSF lets you share your preprints openly. You can also share supplemental data, materials or code associated with your article.')
gettext('TUprints')
gettext('TUprints is the open access repository for all current and former members of the Technical University Darmstadt.')
