#!/bin/bash

if [ "$1" != "" ]; then
  tmp=$1
else
  tmp=$(mktemp)
  cat > $tmp
fi

curl -H "Expect:" -F "text=@/dev/stdin;type=text/plain" \
  http://paste.fulltxt.net/ < $tmp

if [ "$tmp" != "$1" ]; then
  rm $tmp
fi
