# Generated by Django 2.2.1 on 2019-05-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osfdepositpreferences',
            name='on_behalf_of',
            field=models.CharField(blank=True, help_text='If set, your deposits will be associated to this OSF account. This identifier is a string of letters and numbers which can be found in your OSF public profile URL.', max_length=128, null=True, verbose_name='OSF identifier'),
        ),
    ]
