# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 16:11


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='haldepositpreferences',
            name='on_behalf_on',
        ),
        migrations.AddField(
            model_name='haldepositpreferences',
            name='on_behalf_of',
            field=models.CharField(blank=True, help_text='If set, deposits will be associated to this HAL account.', max_length=128, null=True, verbose_name='HAL username'),
        ),
    ]
