# Generated by Django 2.2.6 on 2019-11-20 12:11

from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_verbose_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedpdf',
            name='token',
            field=models.CharField(default=upload.models.new_urlsafe_token, max_length=64),
        ),
    ]
