# Generated by Django 2.1.7 on 2019-02-20 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0002_update_aliases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='stats',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='statistics.AccessStatistics'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='stats',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='statistics.AccessStatistics'),
        ),
        migrations.AlterField(
            model_name='publishercondition',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='publishercopyrightlink',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='publisherrestrictiondetail',
            name='text',
            field=models.TextField(),
        ),
    ]
