# Generated by Django 2.1.7 on 2019-02-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0003_publisher_conditions_as_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishercopyrightlink',
            name='url',
            field=models.URLField(max_length=1024),
        ),
    ]
