# Generated by Django 2.1.7 on 2019-02-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0004_longer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='last_updated',
            field=models.DateTimeField(help_text='last update as reported by RoMEO', null=True),
        ),
    ]
