# Generated by Django 2.1.7 on 2019-02-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0005_publisher_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='essn',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
