# Generated by Django 2.1.7 on 2019-02-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0006_journal_essn'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='romeo_parent_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='romeo_id',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
