# Generated by Django 2.2.1 on 2019-05-27 11:18

from django.db import migrations

def create_zenodo_license_choosers(apps, schema_editor):
    """
    Creates LicenseChooser objects for zenodo repositories as they were hard-coded before introduced model.
    """
    License = apps.get_model('deposit', 'License')
    Repository = apps.get_model('deposit', 'Repository')
    LicenseChooser = apps.get_model('deposit', 'LicenseChooser')
    
    repos_zenodo = Repository.objects.filter(protocol='ZenodoProtocol')
    for repo in repos_zenodo:
        # Default license
        license = License.objects.get(uri='https://dissem.in/deposit/license/zenodo-freetoread-1.0/')
        LicenseChooser.objects.create(repository=repo, license=license, transmit_id='zenodo-freetoread-1.0', default=True, position=0)

        # Non-default licenses
        license_list = [
            ('https://creativecommons.org/publicdomain/zero/1.0/', 'CC0-1.0', 0),
            ('https://creativecommons.org/licenses/by/4.0/', 'CC-BY-4.0', 1),
            ('https://creativecommons.org/licenses/by-sa/4.0/', 'CC-BY-SA-4.0', 2),
            ('https://creativecommons.org/licenses/by-nc/4.0/', 'CC-BY-NC-4.0', 3),
            ('http://creativecommons.org/licenses/by-nd/4.0/', 'CC-BY-ND-4.0', 4),
            ('https://dissem.in/deposit/license/other-open/', 'other-open', 6)
        ]
        for license_item in license_list:
            license = License.objects.get(uri=license_item[0])
            LicenseChooser.objects.create(repository=repo, license=license, transmit_id=license_item[1], position=license_item[2], default=False)


def remove_zenodo_license_choosers(apps, schema_editor):
    """
    Removes license chooser corresponding to zenodo
    """
    
    LicenseChooser = apps.get_model('deposit', 'LicenseChooser')
    LicenseChooser.objects.filter(repository__protocol='ZenodoProtocol').delete()

    

class Migration(migrations.Migration):

    dependencies = [
            ('deposit', '0014_populate_licenses'),
    ]

    operations = [
        migrations.RunPython(create_zenodo_license_choosers, remove_zenodo_license_choosers)
    ]
